Global:
 Updates:
  ShowPercentageOnUpdate: true
 Logging:
  Enabled: false
  MinimumMsForLog: 1000
  LogEvents: true
  LogItems: true
  LogEnchantments: true
 Enchantments:
  CEnchantmentColor: DARK_RED;ITALIC
  CEnchantmentTable: true
  CEnchantingProbability: 10
  MaximumCustomEnchantments: 1000
  RequirePermissions: true
  RepeatPotionEffects: true
  RepeatDelay: 600
Enchantments: